rabbitmq:
  fullnameOverride: "rabbitmq"
  image:
    registry: docker.io
    repository: bitnamilegacy/rabbitmq
    tag: latest # Или конкретную версию типа 3.13-debian-12
    pullPolicy: IfNotPresent

  auth:
    username: coolcinema
    password: coolpassword
    erlangCookie: secretcookie
  persistence:
    enabled: false

  volumePermissions:
    enabled: false

redis:
  fullnameOverride: "redis"

  architecture: standalone

  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0

postgresql:
  fullnameOverride: "postgresql"

  auth:
    username: postgres
    password: postgres
    database: coolcinema
  primary:
    persistence:
      enabled: false

jaeger:
  fullnameOverride: "jaeger"
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    # Включаем UI и OTLP приемник
    config:
      query:
        base-path: /jaeger
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false
